{{- if and .Values.server.auth.initialUsername .Values.server.auth.initialPassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drawboard.localAuthSecretName" . }}
  labels: {{ include "drawboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.server.auth.initialUsername | quote }}
  password: {{ .Values.server.auth.initialPassword | quote }}
{{- end -}}
