{{- if .Values.server.oauth.enabled -}}
{{- $hasSecret := false -}}
{{- range $provider, $cfg := .Values.server.oauth.providers -}}
{{- if $cfg.clientSecret -}}
{{- $hasSecret = true -}}
{{- end -}}
{{- end -}}
{{- if $hasSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drawboard.fullname" . }}-oauth
  labels: {{ include "drawboard.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $provider, $cfg := .Values.server.oauth.providers }}
{{- if $cfg.clientSecret }}
  {{ $provider }}-client-secret: {{ $cfg.clientSecret | quote }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}
