{{- if and (not .Values.jwt.existingSecret) .Values.server.jwtSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drawboard.jwtSecretName" . }}
  labels: {{ include "drawboard.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.server.jwtSecret | quote }}
{{- end -}}
